-- 12. Find the total revenue generated by each employee


SELECT o.order_id,first_name || ' ' || last_name AS employee_name,SUM(quantity * od.unit_price) AS total_revenue
FROM employees e
JOIN orders o
ON e.employee_id = o.employee_id
join order_details od
ON o.order_id = od.order_id
GROUP BY o.order_id